version: '2'
services:
  elasticsearch:
    image: elasticsearch:1.7
    ports:
      - 9200:9200
      - 9300:9300
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
